
  <?php include('C:/xampp/htdocs/GH-client/assets/includes/client-header.php'); ?>
  <div class='client-pin'>
    <h4 class='title'><b>2014 Global Tournaments</b></h4>
    <h5 class='sub-title'><b>Tournaments Schedule</b></h5>
    <p class="info">
      <img src="assets/images/website_sources/leaguepedia.png" height="18px" width="18px">
      Leaguepedia
    </p>
    <div class='client-pin-content-holder' id="tournaments-card">
      <div> <td class="content separator2" id="mainpagecontent" rowspan="3" colspan="2"><div style="background-color: #eaf5fe; text-align: center;"><b>UPCOMING</b></div>
<a href="/Brasil_Gaming_League" title="Brasil Gaming League"><img alt="BGL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/4/4d/BGL_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 15 - Feb 16</div>  <span style="float:right;"><a href="/Brasil_Gaming_League_Arena_3" title="Brasil Gaming League Arena 3">BGL Arena #3</a></span><br>
<a href="/Garena_Tournament" title="Garena Tournament"><img alt="Garena logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/4/40/Garena_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 15 - <i>TBA</i></div>  <span style="float:right;"><a href="/index.php?title=2014_PGS_Spring&amp;action=edit&amp;redlink=1" class="new" title="2014 PGS Spring (page does not exist)">2014 PGS Spring</a></span><br>
<a href="/Garena_Premier_League" title="Garena Premier League"><img alt="Gpllogo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/6/60/Gpllogo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 12 - <i>TBA</i></div>  <span style="float:right;"><a href="/2014_GPL_Spring" title="2014 GPL Spring">2014 GPL Spring</a></span><br>
<a href="/2014_League_of_Legends_Japan_League" title="2014 League of Legends Japan League"><img alt="LJL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/7/7c/LJL_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 9 - Mar 30</div>  <span style="float:right;"><a href="/2014_League_of_Legends_Japan_League/Winter_Season" title="2014 League of Legends Japan League/Winter Season">2014 LJL Winter</a></span><br>
<div style="background-color:#ebfeea; text-align: center;"><b>CURRENT</b></div>
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 1 - Feb 2</div>  <span style="float:right;"><a href="/Razer_League_of_Legends_Clash#1" title="Razer League of Legends Clash">Razer LoL Clash #1</a></span><br>
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 1 - Feb 2</div>  <span style="float:right;"><a href="/FACEIT_Challenger_Invitational" title="FACEIT Challenger Invitational">FACEIT Challenger Invitational</a></span><br>
<a href="/JCG_Premier_League" title="JCG Premier League"><img alt="JCG logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/c/cd/JCG_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Feb 1 - Feb 15</div>  <span style="float:right;"><a href="/2014_JCG_Premier_League/Season_1" title="2014 JCG Premier League/Season 1">2014 JCG Premier League S1</a></span><br>
<a href="/Riot_Games_Inc." title="Riot Games Inc."><img alt="RpPoints.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/8/8c/RpPoints.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 17 - Feb 16</div>  <span style="float:right;"><a href="/NA_Coke_Zero_Challenger_Series/Spring_Series" title="NA Coke Zero Challenger Series/Spring Series">NA Coke Challenger Series #1</a></span><br>
<a href="/League_of_Legends_Championship_Series" title="League of Legends Championship Series"><img alt="LCSlogo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/1/19/LCSlogo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 17 - Apr 6</div>  <span style="float:right;"><a href="/Riot_League_Championship_Series/North_America/2014_Season/Spring_Round_Robin" title="Riot League Championship Series/North America/2014 Season/Spring Round Robin">NA LCS 2014 Spring Season</a></span><br>
<a href="/Riot_Games_Inc." title="Riot Games Inc."><img alt="RpPoints.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/8/8c/RpPoints.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 14 - Feb 14</div>  <span style="float:right;"><a href="/EU_Coke_Zero_Challenger_Series/Spring_Series" title="EU Coke Zero Challenger Series/Spring Series">EU Coke Challenger Series #1</a></span><br>
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 14 - Jul 1</div>  <span style="float:right;"><a href="/Liga_de_Videojuegos_Profesional/Season_6" title="Liga de Videojuegos Profesional/Season 6">LVP Season 6</a></span><br>
<a href="/League_of_Legends_Championship_Series" title="League of Legends Championship Series"><img alt="LCSlogo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/1/19/LCSlogo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 14 - Apr 3</div>  <span style="float:right;"><a href="/Riot_League_Championship_Series/Europe/2014_Season/Spring_Round_Robin" title="Riot League Championship Series/Europe/2014 Season/Spring Round Robin">EU LCS 2014 Spring Season</a></span><br>
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 7 - <i>Present</i></div>  <span style="float:right;"><a href="/2014_Ozone_Masters_League/Summer" title="2014 Ozone Masters League/Summer">Ozone Masters League Summer</a></span><br>
<a href="/Cyber_Games_Arena" title="Cyber Games Arena"><img alt="CGA small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/3/3c/CGA_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Dec 16 - Feb 4</div>  <span style="float:right;"><a href="/2013_CGA_Major_League/Winter" title="2013 CGA Major League/Winter">2013 CML Winter</a></span><br>
<a href="/Turkish_Champions_League" title="Turkish Champions League"><img alt="TCL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b3/TCL_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Dec 1 - Feb 2</div>  <span style="float:right;"><a href="/2014_Turkish_Champions_League/Winter" title="2014 Turkish Champions League/Winter">2014 TCL Winter</a></span><br>
<div style="background-color:#feeeea; text-align: center;"><b>PAST</b></div>
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25"></a><div class="tnl-sedate" style="text-align:center">Jan 29</div>  <span style="float:right;"><a href="/ROCCAT_King_of_the_Hill_2013-2014#Week_6" title="ROCCAT King of the Hill 2013-2014">ROCCAT KOTH Week 6</a></span><br>
<a href="/Intel_Extreme_Masters" title="Intel Extreme Masters"><img alt="Esltumbnail.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/be/Esltumbnail.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 28 - Jan 29</div>  <span style="float:right;"><a href="/IEM_Season_VIII_-_Sao_Paulo" title="IEM Season VIII - Sao Paulo">IEM Season VIII Sao Paulo</a></span><br>
<a href="/EUW_Challenger_Series" title="EUW Challenger Series"><img alt="EUW Challenger Series.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/thumb/7/74/EUW_Challenger_Series.png/25px-EUW_Challenger_Series.png" width="25" height="25" srcset="http://hydra-media.cursecdn.com/lol.gamepedia.com/thumb/7/74/EUW_Challenger_Series.png/38px-EUW_Challenger_Series.png 1.5x, http://hydra-media.cursecdn.com/lol.gamepedia.com/thumb/7/74/EUW_Challenger_Series.png/50px-EUW_Challenger_Series.png 2x"></a>  <div class="tnl-sedate">Jan 25 - Jan 28</div>  <span style="float:right;"><a href="/EUW_Challenger_Series/Week_18_Cup" title="EUW Challenger Series/Week 18 Cup">EUW Challenger Series #18</a></span><br>
<a href="/League_of_Legends_Nova_League" title="League of Legends Nova League"><img alt="LNL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/1/1f/LNL_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 15 - Jan 27</div>  <span style="float:right;"><a href="/2014_LNL_Spring/Promotion" title="2014 LNL Spring/Promotion" class="mw-redirect">2014 LNL Spring Qualifier</a></span><br>
<a href="/Turkish_Champions_League" title="Turkish Champions League"><img alt="TCL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b3/TCL_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 25 - Jan 26</div>  <span style="float:right;"><a href="/2014_Turkish_Champions_League/Spring/Promotion" title="2014 Turkish Champions League/Spring/Promotion">2014 TCL Spring Promotion</a></span><br>
<a href="/JCG_Premier_League" title="JCG Premier League"><img alt="JCG logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/c/cd/JCG_logo_small.png" width="25" height="25"></a>  <div class="tnl-sedate">Jan 25 - Jan 26</div>  <span style="float:right;"><a href="/JCG_Premier_League/Finals" title="JCG Premier League/Finals">JCG Premier L. Grand Finals</a></span><br>
<a href="/LoL_The_Champions" title="LoL The Champions"><img alt="Ogn logo.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/c/ca/Ogn_logo.png" width="25" height="25"></a>  <div class="tnl-sedate">Nov 15 - Jan 25</div>  <span style="float:right;"><a href="/PANDORA.TV_Champions_Winter_2013-2014" title="PANDORA.TV Champions Winter 2013-2014">PANDORA.TV Champions Winter</a></span><br>
</td> </div>
    </div>
  </div>
  <?php include('C:/xampp/htdocs/GH-client/assets/includes/client-footer.php'); ?>
  