<?php include('C:/xampp/htdocs/GH-client/assets/includes/client-header.php'); ?>
<div class='client-pin'>
  <h4 class='title'>
    <a href="http://lol.gamepedia.com/Leaguepedia:Tournaments">  
      <b>Global Tournament Schedule</b>
    </a>
  </h4>
  <p class="info">
    <img src="assets/images/website_sources/leaguepedia.png" height="18px" width="18px">
    Leaguepedia
  </p>
  <div class='client-pin-content-holder' id="tournaments-card">
    <div style="background-color: #eaf5fe; text-align: center;"><b>UPCOMING</b></div>
<a href="/Garena_Tournament" title="Garena Tournament"><img alt="Garena logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/4/40/Garena_logo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 15 - <i>TBA</i></div>&#160;&#160;<span style="float:right;"><a href="/2014_PGS_Spring" title="2014 PGS Spring">2014 PGS Spring</a></span><br />
<a href="/Club_Masters" title="Club Masters"><img alt="ClubMastersLogoSmall.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/bf/ClubMastersLogoSmall.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 13 - <i>TBA</i></div>&#160;&#160;<span style="float:right;"><a href="/SK_Telecom_LTE-A_LoL_Masters_2014" title="SK Telecom LTE-A LoL Masters 2014">SKT LTE-A LoL Masters 2014</a></span><br />
<a href="/Garena_Premier_League" title="Garena Premier League"><img alt="Gpllogo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/6/60/Gpllogo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 12 - <i>TBA</i></div>&#160;&#160;<span style="float:right;"><a href="/2014_GPL_Spring" title="2014 GPL Spring">2014 GPL Spring</a></span><br />
<div style="background-color:#ebfeea; text-align: center;"><b>CURRENT</b></div>
<a href="/2014_League_of_Legends_Japan_League" title="2014 League of Legends Japan League"><img alt="LJL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/7/7c/LJL_logo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 9 - Mar 30</div>&#160;&#160;<span style="float:right;"><a href="/2014_League_of_Legends_Japan_League/Winter_Season" title="2014 League of Legends Japan League/Winter Season">2014 LJ League Winter</a></span><br />
<a href="/Turkish_Champions_League" title="Turkish Champions League"><img alt="TCL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b3/TCL_logo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 8 - Mar 30</div>&#160;&#160;<span style="float:right;"><a href="/2014_Turkish_Champions_League/Spring" title="2014 Turkish Champions League/Spring">2014 TCL Spring</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 8 - Feb 26</div>&#160;&#160;<span style="float:right;"><a href="/NiceGameTV_bigfile_Battle_Royal_Season_3" title="NiceGameTV bigfile Battle Royal Season 3">bigfile Battle Royal Season 3</a></span><br />
<a href="/ESL_Pro_Series" title="ESL Pro Series"><img alt="Epssmalllogo.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/3/32/Epssmalllogo.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 6 - <i>Present</i></div>&#160;&#160;<span style="float:right;"><a href="/National_ESL_Pro_Series/Season_IX" title="National ESL Pro Series/Season IX">EPS NA Season 9</a></span><br />
<a href="/JCG_Premier_League" title="JCG Premier League"><img alt="JCG logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/c/cd/JCG_logo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 1 - Feb 15</div>&#160;&#160;<span style="float:right;"><a href="/2014_JCG_Premier_League/Season_1" title="2014 JCG Premier League/Season 1">2014 JCG Premier League S1</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 22 - <i>Present</i></div>&#160;&#160;<span style="float:right;"><a href="/Colombia_National_League" title="Colombia National League">Colombia National League</a></span><br />
<a href="/Riot_Games_Inc." title="Riot Games Inc."><img alt="RpPoints.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/8/8c/RpPoints.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 17 - Feb 16</div>&#160;&#160;<span style="float:right;"><a href="/NA_Coke_Zero_Challenger_Series/Spring_Series" title="NA Coke Zero Challenger Series/Spring Series">NA Coke Challenger Series #1</a></span><br />
<a href="/League_of_Legends_Championship_Series" title="League of Legends Championship Series"><img alt="LCSlogo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/1/19/LCSlogo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 17 - Apr 6</div>&#160;&#160;<span style="float:right;"><a href="/Riot_League_Championship_Series/North_America/2014_Season/Spring_Round_Robin" title="Riot League Championship Series/North America/2014 Season/Spring Round Robin">NA LCS 2014 Spring Season</a></span><br />
<a href="/Riot_Games_Inc." title="Riot Games Inc."><img alt="RpPoints.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/8/8c/RpPoints.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 14 - Feb 14</div>&#160;&#160;<span style="float:right;"><a href="/EU_Coke_Zero_Challenger_Series/Spring_Series" title="EU Coke Zero Challenger Series/Spring Series">EU Coke Challenger Series #1</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 14 - Jul 1</div>&#160;&#160;<span style="float:right;"><a href="/Liga_de_Videojuegos_Profesional/Season_6" title="Liga de Videojuegos Profesional/Season 6">LVP Season 6</a></span><br />
<a href="/League_of_Legends_Championship_Series" title="League of Legends Championship Series"><img alt="LCSlogo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/1/19/LCSlogo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 14 - Apr 3</div>&#160;&#160;<span style="float:right;"><a href="/Riot_League_Championship_Series/Europe/2014_Season/Spring_Round_Robin" title="Riot League Championship Series/Europe/2014 Season/Spring Round Robin">EU LCS 2014 Spring Season</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Jan 7 - <i>Present</i></div>&#160;&#160;<span style="float:right;"><a href="/2014_Ozone_Masters_League/Summer" title="2014 Ozone Masters League/Summer">Ozone Masters League Summer</a></span><br />
<div style="background-color:#feeeea; text-align: center;"><b>PAST</b></div>
<a href="/North_American_Challenger_League" title="North American Challenger League"><img alt="Nacl small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/3/32/Nacl_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 4 - Feb 10</div>&#160;&#160;<span style="float:right;"><a href="/North_American_Challenger_League_Season_2/Qualifiers" title="North American Challenger League Season 2/Qualifiers">NACL Season 2 Qualifier</a></span><br />
<a href="/Cyber_Games_Arena" title="Cyber Games Arena"><img alt="CGA small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/3/3c/CGA_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Dec 16 - Feb 8</div>&#160;&#160;<span style="float:right;"><a href="/2013_CGA_Major_League/Winter" title="2013 CGA Major League/Winter">2013 CML Winter</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 1 - Feb 2</div>&#160;&#160;<span style="float:right;"><a href="/Razer_League_of_Legends_Clash#1" title="Razer League of Legends Clash">Razer LoL Clash #1</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Feb 1 - Feb 2</div>&#160;&#160;<span style="float:right;"><a href="/FACEIT_Challenger_Invitational" title="FACEIT Challenger Invitational">FACEIT Challenger Invitational</a></span><br />
<a href="/Turkish_Champions_League" title="Turkish Champions League"><img alt="TCL logo small.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b3/TCL_logo_small.png" width="25" height="25" /></a>&#160;&#160;<div class="tnl-sedate">Dec 1 - Feb 2</div>&#160;&#160;<span style="float:right;"><a href="/2014_Turkish_Champions_League/Winter" title="2014 Turkish Champions League/Winter">2014 TCL Winter</a></span><br />
<a href="/index.php?title=File:LeaguesPlaceholder.png&amp;filetimestamp=20120917120226" class="image"><img alt="LeaguesPlaceholder.png" src="http://hydra-media.cursecdn.com/lol.gamepedia.com/b/b4/LeaguesPlaceholder.png" width="25" height="25" /></a><div class="tnl-sedate" style="text-align:center">Jan 29</div>&#160;&#160;<span style="float:right;"><a href="/ROCCAT_King_of_the_Hill_2013-2014#Week_6" title="ROCCAT King of the Hill 2013-2014">ROCCAT KOTH Week 6</a></span><br />

  </div>
  <br/>
  <div class="viewmore">
    <a href="http://lol.gamepedia.com/Leaguepedia:Tournaments">View More<a/>
  </div>
</div>
<?php include('C:/xampp/htdocs/GH-client/assets/includes/client-footer.php'); ?>